### ISSUE TITLE
How do you generate secrets.DEVELOPMENT_CERTIFICATE_DATA?

### ISSUE THREAD

**Issue by Albinzr** [devbotsxyz/import-signing-certificate#3]
how can I convert cert to secrets.DEVELOPMENT_CERTIFICATE_DATA?, Can you explain the process

**Comment by AustinShalit** [comment]
I use:
```
openssl base64 -in <infile> -out <outfile>
```

and then copy the content of the outfile to the secret.

**Comment by Albinzr** [comment]
I think this should to added to docs.
